# Generated by Django 3.1.1 on 2020-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('token', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Сгенеренный токен')),
                ('original_link', models.CharField(db_index=True, max_length=5000, verbose_name='Оригинальная ссылка')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
    ]
